language: node_js
node_js:
  - "6.5.0"

cache:
  directories:
  - node_modules # NPM packages

install:
  - npm install
  - typings install

before_script:
  - npm link
  - npm link teambition-sdk

script:
  - "npm run build_all"
